### ISSUE TITLE
Version history helpers?

### ISSUE THREAD

**Issue by juliendorra** [oliver-oloughlin/kvdex#124]
My understanding is that Deno KV keeps the full history of a given key. (or am I mistaken?)

When using KV directly, we can keep tack of history for example like this: 
https://deno-blog.com/A_Comprehensive_Guide_to_Deno_KV.2023-06-30#tracking-a-records-history

It would be helpful to have higher level functions in kvdex to list the history of a given entry and to retrieve a previous version of a key.

Would it makes sense, or do you think it's better for devs to rely on their own versioning scheme on top of kvdex/kv?

**Comment by oliver-oloughlin** [comment]
If the version history is persisted, that's a lot of extra data being stored. I think it then makes more sense for developers to manage that themselves if they need it. I might add it as an optional feature in the future, I think the idea is pretty good.

**Comment by oliver-oloughlin** [comment]
Btw KV does not persist the history by itself, you still have to manage all that yourself.

**Comment by oliver-oloughlin** [comment]
@juliendorra I'm exploring some ways I could implement version history, but I have a few questions I would like to ask, as it can be done in a few different ways: 

1) How should deleting a document effect its history? I see 3 possibilities: It doesn't affect the history at all, it deletes all the history, or it creates a new history entry with a value of null to indicate it was deleted at that time. 

2) Should history entries contain the versionstamp of the document, or just a timestamp? Adding the versionstamp introduces extra complexity and delay, while just having a timestamp is much easier and more robust against consistency issues.

Right now I'm leaning towards 1) Create an entry with null value to record deletes, 2) Just have timestamp.

**Comment by oliver-oloughlin** [comment]
I've added version history support in the release (v0.25.1)

**Comment by oliver-oloughlin** [comment]
It was my intuition that a version history should persist all states of a document, deleted also being a state. The way I have implemented it differs slightly from my original thinking, where instead of a null or empty value, a history entry has a type property, specifying if the state is a write or a delete. Write entries have a copy of the document value, while delete entries do not.

My reason for doing this is that it enables a wider range of functionality, where every state is accounted for. For example if you were to delete a document, and then later write to that same id, you would be able to see the entire history of that id instead of loosing it. I plan to add some more utility functions to allow for deleting a document's history. Right now history is persisted as long as history is enabled for the collection, and can only be deleted by wiping the entire database (`db.wipe()`)

**Comment by oliver-oloughlin** [comment]
After some initial attempts it turns out it's actually harder to delete history on deleting a document instead of recording the delete. This is because of the history being a range of multiple entries, requiring every entry to first be read using a list iterator, and then deleting the key for every entry.

**Comment by juliendorra** [comment]
If you come from a git perspective, the persistent history fits the mental model, for sure!

> a history entry has a type property, specifying if the state is a write or a delete. Write entries have a copy of the document value, while delete entries do not.

I'll test using that! Your implementation might fit my use case better, especially in terms of listing the last versions, listing the document without manually filtering versions, etc.

My only (big) issue is that it is a legal obligation to be able to delete all personal data of an user in EU (GDPR), under the penalty of quite heavy fines, and so I ultimately will need a way to delete things that can be considered personal data for good without deleting the whole db 😅 (By the way as an user, I like the idea in the GDPR that services should keep my data only as long as its needed and delete on demand!)

I hope you'll find a way to allow deleting the whole content's history of a particular document. Maybe there's two use case here: 
- Totally deleting any trace (especially for legal GDPR reasons)
- Only keeping the last entry as a delete entry optionally, so the the content is gone but the id is kept. Might be good for non-GDPR, internal confidential use cases. (ie. someone entered data that they shouldn't have and it needs removal, but we want to keep a trace the document existed.

wipeEntireHistory versus emptyContentHistory maybe?

**Comment by oliver-oloughlin** [comment]
I'm just going to reopen this issue as there are still some specifics that should be solved.

I see your point about GDPR, it's definitely an important concern to consider. It is now possible to delete a documents history. I'm wondering if it makes sense to also include the possibility of deleting a document's history when deleting the document itself, through an option like `deleteHistory: true`. But this would change all the `delete...()` APIs, and would mean a breaking change for `delete()`, so I'm a little unsure if it's necessary, especially since it's only a slight enhancement to utility, and not a new feature being enabled.

When it comes to keeping just the last delete entry, that shouldn't be too difficult, although I think the API is getting a little cluttered with delete functions now, so I would probably implement it through options for the existing `deleteHistory()` instead.

**Comment by juliendorra** [comment]
Yes, it's a bit complex to do cleanly in terms of API because there's 3 different that I see a dev doing / needing to do:

1. just mark a document as deleted = add a delete entry to history 
2. also delete history itself, keeping the last delete entry
3. wipe all trace of this document existence

Are 1 and 2 the same with an option? It feels like 3 is the one apart?

**Comment by oliver-oloughlin** [comment]
`findHistory()` now supports pagination and filtering in the latest release (v0.27.0).
Note that this also brings a breaking change to the return type of the method, by making it follow the same signature as other pagination-supported methods that return a result and cursor.

Please let me know if any additional related issues were to arise, otherwise I think I will deem this feature as complete for the time being.
