### ISSUE TITLE
Find by more than one secondary indices?

### ISSUE THREAD

**Issue by juliendorra** [oliver-oloughlin/kvdex#134]
I'm not sure if there would be a speed optimization possible underneath, but it would be useful to ask kvdex to find documents by more than one secondary indices:

`db.versioneddocuments.findBySecondaryIndices( [  ["document",  "myDoc"], [ "version", "12"],  ]
`
That would avoid doing a filter on the whole list of documents.

**Comment by oliver-oloughlin** [comment]
I've thought about it before, but as far as I know there really isn`t any efficient way of doing it. Doing multiple layers of indexing would have an exponential relationship with storage space.

I see three possible alternatives to storing layered indices: 1) Simply find by a single secondary index + filter. 2) Run two findBySecondaryIndex methods, one for each index, and then find the documents that exist in both result sets. Both of these methods should be possible with the current functionality. 3) Create a new field for the model that is some aggregate of the two indices you want to search by, and make it a secondary index (or primary). Then find by that aggregate index instead.

I think in most situations there is only a need to find by a single index, and when there is a need for more than that it is often performant enough to filter since at that point you have already greatly reduced the dataset. Otherwise for special use cases it's still possible to do some clever tricks with indexing to make fast queries.
