### ISSUE TITLE
Zod ext error

### ISSUE THREAD

**Issue by hwcwy** [oliver-oloughlin/kvdex#174]
Deno 1.40.4
![image](https://github.com/oliver-oloughlin/kvdex/assets/74729240/dd9f3b92-f803-4a0f-82b8-b93f0ff105d9)

**Comment by hwcwy** [comment]
I found that this problem also occurs when I use "npm:zod"

![image](https://github.com/oliver-oloughlin/kvdex/assets/74729240/a816fe8e-a769-4145-8dab-66f5298b3c7c)

**Comment by oliver-oloughlin** [comment]
For me when I tried this I only got the issue when importing zod from deno.land/x, not when using npm:zod. I'm also on Deno 1.40.4. I think this is very likely due to the Deno extension/linter not being updated for jsr imports yet. One of the maintainers mentioned in the Discord that it would take them a few days to get it working.

**Comment by hwcwy** [comment]
Thank you for answering my question. I will close this issue when the problem is solved😊

**Comment by hironichu** [comment]
I can confirm it seems to be fixed using the npm:zod package with latest deno update ;)

**Comment by hwcwy** [comment]
Yes, this issue can now be fixed using npm:zod 👌
