### ISSUE TITLE
Primary indexes specific error messages

### ISSUE THREAD

**Issue by denyncrawford** [oliver-oloughlin/kvdex#206]
Would it be possible to enhance the error messages to provide more detailed information about the failing fields during operations? Presently, the error response is limited to:

```
{
  "error": {
    "ok": false
  }
}
```
While this is ok for operations with only a few potential failure points, it becomes challenging to pinpoint errors within larger DTOs.

> I'm not sure if this is a limitation specific to Deno KV, but it would be great if it could be improved if possible.

**Comment by oliver-oloughlin** [comment]
This is a good point, thanks for raising it. As for right now, I don't see any easy way of implementing more nuanced error messages without making significant sacrifices to performance. The reason is that checking for collisions on unique indices relies on the `kv.atomic().check()` operation. For multiple indices, there will be multiple `check()` operations combined together with the `set()` operation. The result when committing the operation is simply the commit error object `{ "ok": false }` or a commit result with the signature `{ ok: true, versionstamp: string }`. Because KV gives no feedback on which check operation that fails, it doesn't seem possible to me as of now to forward this error response with any more nuance sadly.

**Comment by oliver-oloughlin** [comment]
Closing this for now as there is no indication that this will change.
